VERSION="2.4.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
	"GD7G6ZAUGH2CGO3LIJO5JDVGSNAHKDIQO6GXDNEWD2N2JI7EUKI4ZYJL",
  	"GCOFMGR57KHY7AVLFX7NARP25ZIMOLYJRNLNMNBXZ3BFL2VF5M3IBHHF",
]

[DOCUMENTATION]
ORG_NAME="Manangos"
ORG_URL="https://manangos2.tk"
ORG_KEYBASE="https://www.manangos2.tk"
ORG_LOGO="https://manangos2.tk/wp-content/uploads/2022/03/Mango-Favicon.png"
ORG_DESCRIPTION="Manangos V2 better than ever!"
ORG_OFFICIAL_EMAIL="realmayocoin@gmail.com"
ORG_GITHUB="https://github.com/IceSmash2/manangos-TipBot/"

[[PRINCIPALS]]
name="Slurpee"
email="realmayocoin@gmail.com"

[[CURRENCIES]]
code="Manangos"
issuer="GD7G6ZAUGH2CGO3LIJO5JDVGSNAHKDIQO6GXDNEWD2N2JI7EUKI4ZYJL"
name="Manangos"
desc="Manangos V2 better than ever!"
image="https://manangos2.tk/wp-content/uploads/2022/03/Mango-Favicon.png"
display_decimals=6
conditions="There will be only 52 Billion Manangos in existence."
fixed_number=52000069420
[[CURRENCIES]]
code="Manangos"
issuer="GD7G6ZAUGH2CGO3LIJO5JDVGSNAHKDIQO6GXDNEWD2N2JI7EUKI4ZYJL"
name="Manangos"
desc="Manangos V2 better than ever!"
image="https://manangos2.tk/wp-content/uploads/2022/03/manangos_logo_animated.gif"
display_decimals=6
conditions="There will be only 52 Billion Manangos in existence."
fixed_number=52000069420